### ISSUE TITLE
"Undeffined/NaN" XP bug

### ISSUE THREAD

**Issue by EzraTan1101** [piano1029/ClannySystems#48]
sometimes when you give XP it fails to process and changed the user's XP to Undefined/NaN (mostly on new members)

pretty annoying bug because you have to manually set their XP, please fix this.
![image](https://user-images.githubusercontent.com/83954184/151522380-35df5cec-e3c9-4a95-9e35-e224edec211b.png)

**Comment by piano1029** [comment]
Fixed in V10, will close this issue once V10 is released
