### ISSUE TITLE
API Token Ephemeral Messages 

### ISSUE THREAD

**Issue by jackdotink** [piano1029/ClannySystems#49]
Sending API tokens in DMs is dangerous. The messages are there forever. Instead use discord's ephemeral messages, where you can only view the message for a limited time, and it doesn't save. 

This would slightly improve security.

**Comment by piano1029** [comment]
ClannyV3 doesn't use Interactions, so we cant use ephemeral messages in there. ClannyV10 does use Interactions, so we wont send API keys through Discord at all and instead do it through a dashboard.

**Comment by piano1029** [comment]
(ClannyV10 isn't out yet btw)
