### ISSUE TITLE
Let us add our own bots

### ISSUE THREAD

**Issue by phyouthcenter1** [piano1029/ClannySystems#58]
Why:

This would be easier on you since you don't have to manually add every bot
We would have control over the account and we would feel safer

**Comment by piano1029** [comment]
We used to use that until it had been made impossible by Roblox

https://discord.com/channels/683722162871205983/684785962592632931/951023934336286721
https://devforum.roblox.com/t/ip-changes-invalidate-cookie/1700515

**Comment by phyouthcenter1** [comment]
I have done it before personally so I dont see how it wouldnt work.

**Comment by piano1029** [comment]
The bot can’t use your IP address, so if you send the bot a token and the bot uses it gets made useless by Roblox.

it had worked before but due to recent changes by roblox it’s impossible now
