### ISSUE TITLE
bot

### ISSUE THREAD

**Issue by Naraphat12** [piano1029/ClannySystems#68]

**Comment by piano1029** [comment]
What?

**Comment by Naraphat12** [comment]
Are you here?

**Comment by piano1029** [comment]
I'm still alive yes

**Comment by Naraphat12** [comment]
![image](https://user-images.githubusercontent.com/114068102/227642976-44bcdd81-e69a-4033-bce4-7c23087e3dd0.png)

What happened, Can't /promote

**Comment by piano1029** [comment]
Not something for this GitHub page, you are already in the Discord support server, that's for support.
